FROM python:3.10-slim

WORKDIR /app

# 安装依赖
COPY ./api/gateway/requirements.txt /app/requirements.txt

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY ./config /app/config
COPY ./shared /app/shared
COPY ./static /app/static
COPY ./api/gateway /app/api/gateway

# 暴露端口和设置环境
EXPOSE 8000
ENV PYTHONPATH=/app
CMD ["python", "-m", "uvicorn", "api.gateway.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 