FROM python:3.10-slim

WORKDIR /app

# 安装依赖
COPY ./requirements.txt /app/requirements.txt

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制服务代码
COPY ./ /app/service

# 暴露端口（具体端口会由环境变量设置）
EXPOSE 8001 8002

# 设置环境变量
ENV PYTHONPATH=/app

# 启动模型服务
CMD uvicorn service.main:app --host 0.0.0.0 --port $MODEL_PORT --reload 